export { generateOrderNumber } from './generateOrderNumber'
export { populateItemPrices } from './populateItemPrices'
export { validateOrderItems } from './validateOrderItems'
export { assignCustomer } from './assignCustomer'
export { updateInventory } from './updateInventory'
export { handleStatusChange } from './handleStatusChange'
